/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SupplierRole;

import business.Business;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import system.Enterprise.Enterprise;
import system.Location.Location;
import system.NetWork.NetWork;
import system.NetWork.NetWorkDirectory;

/**
 *
 * @author Administrator
 */
public class CreateStateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateStateJPanel
     */
    JPanel container;
//    NetWorkDirectory netWorkDirectory;    
//     DefaultMutableTreeNode node;
  Enterprise e;
    Business business;
    public CreateStateJPanel(
           JPanel container,
//            NetWorkDirectory netWorkDirectory
          Enterprise e,
          Business business) {
        initComponents();
        this.container =container;
//        this.netWorkDirectory= netWorkDirectory;
       this.business = business;
       this.e=e;
        populateComboBox();
    }
      private void populateComboBox(){
        networkJComboBox.removeAllItems();
//        enterpriseTypeJComboBox.removeAllItems();
        
        for (NetWork network : business.getNetWorkDirectory().getNetWorkList()){
            if(e.getLocation().getCountry().equals(network.getName()))
            networkJComboBox.addItem(network);
        }
        
//        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()){
//            enterpriseTypeJComboBox.addItem(type);
//        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        creJButton = new javax.swing.JButton();
        stateJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        creJButton.setText("Change");
        creJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creJButtonActionPerformed(evt);
            }
        });
        add(creJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));
        add(stateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 80, -1));

        jLabel2.setText("State:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Change State");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel3.setText("Network");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void creJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creJButtonActionPerformed
        // TODO add your handling code here:

        if (stateJTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid name!");
        } else {
            
//            Location l= netWork.getLocationDirectory().creLocation();
       NetWork netWork = (NetWork)networkJComboBox.getSelectedItem();
             Location l= new Location();
             boolean checkL = netWork.getLocationDirectory().checkLocationName(stateJTextField.getText());
                if (checkL == false) {
                    netWork.getLocationDirectory().getLocationList().add(l);
                }
//            SubLocation sbl = l.creSubLocation();
            l.setName(stateJTextField.getText());
            l.setState(stateJTextField.getText());
            e.setLocation(l);
            e.getLocation().setCountry(netWork.getName());
            e.getLocation().setState(l.getState());
//            l.getLocation().add(sbl);
//            netWork.setLocation(l);
//            popdata();
        }
    }//GEN-LAST:event_creJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton creJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField stateJTextField;
    // End of variables declaration//GEN-END:variables
}
