/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Business.DB4OUtil.DB4OUtil;
import javax.swing.JOptionPane;
import system.UserAccount.UserAccount;
import business.Business;
import java.awt.CardLayout;
import system.Enterprise.Enterprise;
import system.NetWork.NetWork;
import system.Organization.Organization;

/**
 *
 * @author Administrator
 */
public class MainJFram extends javax.swing.JFrame {

    /**
     * Creates new form MainJFram
     */
    Business business;
    Organization organization;
    private DB4OUtil db = new DB4OUtil();

    public MainJFram() {
        initComponents();
//        business = ConfigureABusiness.configureABusiness() ;
        business = db.retrieveSystem();
        logoutJButton.setVisible(false);
        logJPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        registerJButton2 = new javax.swing.JButton();
        loginJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        logJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwardJPasswordField = new javax.swing.JPasswordField();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerJButton2.setText("Register");
        registerJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(registerJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 69, -1));

        logoutJButton.setText("Log out");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        logJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("UserName:");
        logJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        logJPanel.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 81, -1));

        jLabel2.setText("Password:");
        logJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        passwardJPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwardJPasswordFieldActionPerformed(evt);
            }
        });
        logJPanel.add(passwardJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 81, -1));

        jPanel1.add(logJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 140));

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void registerJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButton2ActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        //        Person p = business.getPersonDirectory().crePerson(Person.Type.User);
//        UserAccount ua = business.getUserAccountDirectoty().creUserAccount();

        RegisterJPanel register = new RegisterJPanel(container, business);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Register", register);
        layout.next(container);
        loginJButton.setVisible(false);
        registerJButton2.setVisible(false);
        logoutJButton.setVisible(true);
        logJPanel.setVisible(false);
    }//GEN-LAST:event_registerJButton2ActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO add your handling code here:
//        container.removeAll();
//        UserAccount ua = business.getUserAccountDirectoty().validate(userNameJTextField.getText(), passwardJPasswordField.getText());
//        if (ua != null) {
//            //            Business.out.println("ua's type is"+ ua.getType());
//            CardLayout layout = (CardLayout)container.getLayout();
//            container.add("WorkArea", ua.getRole().fetchPanel(container, ua,organization, business));
//            layout.next(container);
//        } else{
//            JOptionPane.showMessageDialog(null, "Worng UserName or Password!");
//        }
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwardJPasswordField.getPassword();
        String password = String.valueOf(passwordCharArray);
        //Step1: Check in the EcoSystem
        UserAccount userAccount= business.authenticateUser(userName, password);
        if(userAccount ==null){
             Organization inAmazonOrganization=null;
        for(Organization o: business.getDepartmentDirectory().getDepartmentList()){
        userAccount = o.authenticateUser(userName, password);
        if(userAccount !=null){
        inAmazonOrganization=o;
        break;
        }
        }
        }
        //Step2: If user account is not in the system's user account directory
   
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        if (userAccount == null) {
//             for(Organization or: business.getDepartmentDirectory().getDepartmentList()){
//        userAccount = or.authenticateUser(userName, password);
//        if(userAccount!=null){
//        inAmazonOrganization= or;
//        break;
//        }else {
          for (NetWork network : business.getNetWorkDirectory().getNetWorkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = enterprise.authenticateUser(userName, password);
                    if (userAccount != null) {
                        inEnterprise = enterprise;
                        break;
                    } else {
                        for (Organization organization : enterprise.getDepartmentDirectory().getDepartmentList()) {
                            userAccount = organization.authenticateUser(userName, password);
                            if (userAccount != null) {
                                inEnterprise = enterprise;
                                inOrganization = organization;
                                break;
                            }
                        }
                    }
                    if (inOrganization != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }
//        }
//             }  
          
            
        }

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid Credentials!");
        } else {
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea", userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, business));
            layout.next(container);
            registerJButton2.setVisible(false);
            loginJButton.setVisible(false);
            logoutJButton.setVisible(true);
            logJPanel.setVisible(false);
        }
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void passwardJPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwardJPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwardJPasswordFieldActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        userNameJTextField.setText("");
        passwardJPasswordField.setText("");
        db.storeSystem(business);
        loginJButton.setVisible(true);
        registerJButton2.setVisible(true);
        logoutJButton.setVisible(false);
        logJPanel.setVisible(true);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFram().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel logJPanel;
    private javax.swing.JButton loginJButton;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwardJPasswordField;
    private javax.swing.JButton registerJButton2;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
