/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import userInterface.CustomerRole.CustomerRegisterJPanel;
import business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Enterprise.Enterprise;
import system.NetWork.NetWork;
import system.Person.Person;
import system.Role.TempRole;

import system.UserAccount.UserAccount;
import userInterface.TempRole.RetalierRegisterJPanel;
import userInterface.TempRole.TempWorkAreaJPanel;

/**
 *
 * @author Administrator
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    JPanel container;
    UserAccount userAccount;
    Business business;
    public RegisterJPanel( JPanel container,
    Business business) {
        initComponents();
        this.container = container;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierRegisterJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        customerRegisterJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierRegisterJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierRegisterJButton.setText("Enterprise Register");
        supplierRegisterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierRegisterJButtonActionPerformed(evt);
            }
        });
        add(supplierRegisterJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Register");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        customerRegisterJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerRegisterJButton.setText("Customer Register");
        customerRegisterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRegisterJButtonActionPerformed(evt);
            }
        });
        add(customerRegisterJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void supplierRegisterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierRegisterJButtonActionPerformed
        // TODO add your handling code here:
           Person p =business.getPersonDirectory().crePerson();
//     for(NetWork n: business.getNetWorkDirectory().getNetWorkList()){
//     for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
//     UserAccount ua = new UserAccount();
//     e.getUserAccountDirectoty().creUserAccount("", "", p, new TempSupplierRole());
//         ua.setRole(new TempSupplierRole());
//     TempSupplierWorkAreaJPanel tempSupplierWorkAreaJPanel = new TempSupplierWorkAreaJPanel(container,p,business);
//        CardLayout layout = (CardLayout) container.getLayout();
//        container.add("TempSupplierWorkAreaJPanel", tempSupplierWorkAreaJPanel);
//        layout.next(container);
//     }
//     }
             RetalierRegisterJPanel retalierRegister = new RetalierRegisterJPanel(container,p,business);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("RegisterRetalier", retalierRegister);
        layout.next(container);
       
    }//GEN-LAST:event_supplierRegisterJButtonActionPerformed

    private void customerRegisterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRegisterJButtonActionPerformed
        // TODO add your handling code here:
//         UserAccount ua = business.getUserAccountDirectoty().creUserAccount();
       Person p = business.getPersonDirectory().crePerson();
//        Customer c= business.getCustomerDirectory().creCustomer(p);
        CustomerRegisterJPanel customerRegisterJPanel = new CustomerRegisterJPanel(container,p,business);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("RegisterCustomer", customerRegisterJPanel);
        layout.next(container);
    }//GEN-LAST:event_customerRegisterJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerRegisterJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton supplierRegisterJButton;
    // End of variables declaration//GEN-END:variables
}
