/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AmazonRole.SystemAdminRole;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import system.Location.Location;
import system.Location.SubLocation;
import system.NetWork.NetWork;
import system.NetWork.NetWorkDirectory;

/**
 *
 * @author Administrator
 */
public class CreateCountryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCountryJPanel
    
     */
    JPanel container;
    NetWorkDirectory netWorkDirectory;
    public CreateCountryJPanel(
           JPanel container,
    NetWorkDirectory netWorkDirectory   ) {
        initComponents();
        this.container =container;
        this.netWorkDirectory = netWorkDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        creJButton = new javax.swing.JButton();
        countryJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        creJButton.setText("Create");
        creJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creJButtonActionPerformed(evt);
            }
        });
        add(creJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
        add(countryJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 80, -1));

        jLabel2.setText("Country:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create Country");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void creJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creJButtonActionPerformed
        // TODO add your handling code here:

        if (countryJTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid name!");
        } else {
//            NetWork netWork = netWorkDirectory.creNetWork(countryJTextField.getText());
              NetWork  n = new NetWork(countryJTextField.getText());
                boolean checkNetWork = netWorkDirectory.checkNetWorkName(countryJTextField.getText());
                if (checkNetWork == false) {
                    netWorkDirectory.getNetWorkList().add(n);
                }
//            netWork.setCountry(countryJTextField.getText());
//            netWork.getLocation().setCountry(countryJTextField.getText());
//            Location l= netWork.getLocationDirectory().creLocation();
//            l.setCountry(countryJTextField.getText());
////
//            netWork.setLocation(l);
//            popdata();
        }
    }//GEN-LAST:event_creJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField countryJTextField;
    private javax.swing.JButton creJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
