/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AmazonRole.SystemAdminRole;

import business.Business;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import system.Employee.Employee;
import system.Enterprise.Enterprise;
import system.NetWork.NetWork;
import system.Role.ShippingEnterpriseRole;
import system.Role.SupplierRole;
import system.UserAccount.UserAccount;

/**
 *
 * @author Administrator
 */
  
public class ManageEnterprisePartnerAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageShippingAdminJPanel
     */
    JPanel container;
    Business business;
    public ManageEnterprisePartnerAdminJPanel(
              JPanel container,
    Business business) {
        initComponents();
            this.container = container;
        this.business = business;
       populateNetWorkComboBox();
    }
      private void populateNetWorkComboBox(){
        networkJComboBox.removeAllItems();
      
        
        for (NetWork network : business.getNetWorkDirectory().getNetWorkList()){
            networkJComboBox.addItem(network);
        }
      
        
    }
       private void populateEnterpriseComboBox(NetWork network){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseJComboBox.addItem(enterprise);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        usernameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 110, 20));

        jLabel3.setText("Enterprise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 110, -1));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel1.setText("Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel5.setText("Admin Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 240, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Manage  Enterprise Partner Admin");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        NetWork network = (NetWork)networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        container.remove(this);
        ((CardLayout)container.getLayout()).previous(container);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

        if (enterprise == null){
            JOptionPane.showMessageDialog(null, "No network or enterprise type selected!");
            return;
        }

        String username = usernameJTextField.getText();
           boolean check =enterprise.getUserAccountDirectoty().checkUserName(username);
      if(check==true){
                 JOptionPane.showMessageDialog(null, "UserName has exsited!");
               
             }else{
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String empName = nameJTextField.getText();

        Employee employee = enterprise.getEmployeeDirectory().creEmployee();
        employee.setEmpName(empName);
        if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.ShippingEnterprise)){
        UserAccount ua = enterprise.getUserAccountDirectoty().creUserAccount(username, password, employee, new ShippingEnterpriseRole());
    
//        System.out.print("enterprise's userAccountDirectory"+enterprise.getUserAccountDirectoty()+ua);
        ua.setUserName(username);
        ua.setPassword(password);
        ua.setPerson(employee);
        ua.setRole(new ShippingEnterpriseRole());
        ua.setEnterprise(enterprise);
        } else{
         UserAccount ua = enterprise.getUserAccountDirectoty().creUserAccount(username, password, employee, new SupplierRole());
        ua.setUserName(username);
        ua.setPassword(password);
        ua.setPerson(employee);
        ua.setRole(new SupplierRole());
        ua.setEnterprise(enterprise);
        }
      }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
