/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AmazonRole.SystemAdminRole;

import business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import system.Enterprise.Enterprise;
import system.Location.Location;
import system.NetWork.NetWork;
import system.NetWork.NetWorkDirectory;
import system.Role.SupplierRole;
import system.UserAccount.UserAccount;
import system.WorkQueue.WorkRequest;

/**
 *
 * @author Administrator
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    JPanel container;
    NetWorkDirectory netWorkDirectory;
    NetWork netWork;
    Business business;
Enterprise enterprise;
UserAccount ua;
    public ManageEnterpriseJPanel(JPanel container,Enterprise enterprise,
           Business business,
           UserAccount ua) {
        initComponents();
        this.container = container;
        this.enterprise =enterprise;
        this.business = business;
        this.ua=ua;
        this.netWorkDirectory =business.getNetWorkDirectory();
//        populateCountry();

    }
//
//    private void populateCountry() {
//       countryJComboBox.removeAllItems();
//        for (NetWork nw : business.getNetWorkDirectory().getNetWorkList()) {
//            countryJComboBox.addItem(nw);
//           
//           
//        }
//    }
//    private void createEnterprise() {
//      
//        if (enterpriseJTextField.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Invalid name!");
//        }else{
//          NetWork network = (NetWork) countryNameJComboBox.getSelectedItem();
//          if(network!=null){
//        Enterprise enterprise = network.createEnterprise(enterpriseJTextField.getText());
//        enterprise.setEnterpriseName(enterpriseJTextField.getText());
//        JOptionPane.showMessageDialog(null, "enterprise created!");
//    }}
//    }
//    private void populateTableData(NetWork nw) {
//        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();
//        model.setNumRows(0);
//        for (Enterprise enterprise : nw.getEnterpriseDirectory().getEnterpriseList()) {
//            Object[] row = new Object[6];
//            row[0] = enterprise.getEnterpriseName();
//            row[1] = enterprise.get;
//            row[2] = nw.getCountryName();
//            model.addRow(row);
//        }
//
//    }
//    private void populateTableData() {
//        DefaultTableModel model = (DefaultTableModel) enterprisewrJTable.getModel();
//        model.setNumRows(0);
////        for(Enterprise e: personDirectory.getPersonList()){
////            if(p instanceof AdminPerson){
//         for (WorkRequest wr :business.getWorkQueue().getWorkRequestList() ) {
//            Object[] row = new Object[7];
//            row[0] = wr.getSender().getEnterprise().getEnterpriseName();    // don't need to get message
//            row[1] = wr.getSender().getUserName();
//            row[2] = wr.getSender().getEnterprise().getLocation().getCountry();
//            row[3]=wr.getSender().getEnterprise().getLocation().getState();
//            row[4] = wr.getSender().getEnterprise().getLocation().getCity();
//            row[5]=wr.getSender().getRole();
//            row[6]=wr.getStatus();
//            model.addRow(row);
//        }
//            }
//        }
//       
//    }

    /**
     * private void createEnterprise(NetWork netWork){ netWork =
     * (NetWork)countryNameJComboBox.getSelectedItem(); Enterprise enterprise =
     * netWork.createEnterprise();
     * enterprise.setEnterpriseName(enterpriseJTextField.getText()); }
     *
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addShippingEnterpriseJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        manageShippingAdminJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Manage Enterprise Partner");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        addShippingEnterpriseJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addShippingEnterpriseJButton.setText("Add Enterprise Partner");
        addShippingEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShippingEnterpriseJButtonActionPerformed(evt);
            }
        });
        add(addShippingEnterpriseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 290, -1));

        manageEnterpriseJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageEnterpriseJButton.setText(" Handle Enterprise Request");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });
        add(manageEnterpriseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 290, -1));

        manageShippingAdminJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageShippingAdminJButton.setText("Manage Enterprise Admin");
        manageShippingAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageShippingAdminJButtonActionPerformed(evt);
            }
        });
        add(manageShippingAdminJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addShippingEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShippingEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
       AddEnterpriseJPanel addShippingEnterpriseJPanel = new AddEnterpriseJPanel(container,business);
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("AddShippingEnterpriseJPanel",addShippingEnterpriseJPanel);
        layout.next(container);

    }//GEN-LAST:event_addShippingEnterpriseJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
        HandleRequestJPanel handleSupplierRequestJPanel = new HandleRequestJPanel(container,business,business.getNetWorkDirectory(),ua);
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("HandleSupplierRequestJPanel",handleSupplierRequestJPanel);
        layout.next(container);

    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void manageShippingAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageShippingAdminJButtonActionPerformed
        // TODO add your handling code here:
        
        ManageEnterprisePartnerAdminJPanel manageShippingAdminJPanel = new ManageEnterprisePartnerAdminJPanel(container,business);
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("ManageShippingAdminJPanel",manageShippingAdminJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageShippingAdminJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addShippingEnterpriseJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageShippingAdminJButton;
    // End of variables declaration//GEN-END:variables
}
