/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AmazonRole.SystemAdminRole;

import userInterface.AmazonRole.HRManagerRole.ManageUserAccountJPanel;
import userInterface.AmazonRole.HRManagerRole.ManageEmployeeJPanel;
import userInterface.AmazonRole.HRManagerRole.ManageOrganizationJPanel;
import business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Employee.EmployeeDirectory;
import system.Enterprise.Enterprise;
import system.Enterprise.EnterpriseDirectory;
import system.NetWork.NetWork;
import system.UserAccount.UserAccount;

/**
 *
 * @author Administrator
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel container;
   Business business;
    UserAccount ua;
    NetWork netWork;
    EmployeeDirectory employeeDirectory;
    Enterprise enterprise;
    public SystemAdminWorkAreaJPanel(JPanel container,
    Business business, UserAccount ua) {
        initComponents();
        this.container = container;
        this.business = business;
        this.ua = ua;
        this.employeeDirectory = business.getEmployeeDirectory();
//      enterprise = business.getEnterprise();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manaNetWorkJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        manaNetWorkJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manaNetWorkJButton.setText("Manage NetWork");
        manaNetWorkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manaNetWorkJButtonActionPerformed(evt);
            }
        });
        add(manaNetWorkJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        manageEnterpriseJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });
        add(manageEnterpriseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manaNetWorkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manaNetWorkJButtonActionPerformed
        // TODO add your handling code here:
          ManageNetWorkJPanel manageNetWorkJPanel = new ManageNetWorkJPanel(container,business.getNetWorkDirectory());
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("ManageNetWorkJPanel",manageNetWorkJPanel);
        layout.next(container);
    }//GEN-LAST:event_manaNetWorkJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
          ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(container,enterprise,business,ua);
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("ManageEnterpriseJPanel",manageEnterpriseJPanel);
        layout.next(container);

    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manaNetWorkJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    // End of variables declaration//GEN-END:variables
}
