/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SupplierRole.SalesDeptRole;

import business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Enterprise.Enterprise;
import system.Organization.Organization;
import system.UserAccount.UserAccount;

/**
 *
 * @author Administrator
 */
public class SalesDeptWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesDeptWorkAreaJPanel
     */
      JPanel userProcessContainer;
   Business business;
   UserAccount ua;
   Enterprise e;
   Organization o;
    public SalesDeptWorkAreaJPanel(JPanel userProcessContainer,UserAccount ua,
   Business business,Enterprise e, Organization o) {
        initComponents();
          this.userProcessContainer =userProcessContainer;
        this.ua =ua;
        this.business= business;
        this.e=e;
            msdpNameJLabel.setText(ua.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browsePCJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        msdpNameJLabel = new javax.swing.JLabel();
        manageCustomerOrderJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        browsePCJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        browsePCJButton.setText("Manage Supplier Product Catalog >>");
        browsePCJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsePCJButtonActionPerformed(evt);
            }
        });
        add(browsePCJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area (SalesDept Role) :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        msdpNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(msdpNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 140, 30));

        manageCustomerOrderJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageCustomerOrderJButton.setText("Manage Customer Order >>");
        manageCustomerOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerOrderJButtonActionPerformed(evt);
            }
        });
        add(manageCustomerOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 320, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void browsePCJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsePCJButtonActionPerformed
        // TODO add your handling code here:
        BrowseProductCatalogJPanel bpcjp = new BrowseProductCatalogJPanel(userProcessContainer, e);
        userProcessContainer.add("BrowseProductCatalogJPanel", bpcjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_browsePCJButtonActionPerformed

    private void manageCustomerOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerOrderJButtonActionPerformed
        // TODO add your handling code here:
        ManageCustomerOrderJPanel manageCustomerOrderJPanel = new ManageCustomerOrderJPanel(userProcessContainer,business, e);
        userProcessContainer.add("ManageCustomerOrderJPanel", manageCustomerOrderJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomerOrderJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browsePCJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCustomerOrderJButton;
    private javax.swing.JLabel msdpNameJLabel;
    // End of variables declaration//GEN-END:variables
}
