/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package userInterface.CustomerRole.Login;

import business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Customer.Customer;
import system.Customer.CustomerDirectory;
import system.Supplier.SupplierDirectory;
import system.UserAccount.UserAccount;

/**
 *
 * @author Rushabh
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    SupplierDirectory supplierDir;
    Business business;
    Customer customer;
    CustomerDirectory customerDirectory;
    UserAccount userAccount;

    /**
     * Creates new form ProductManagerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
//        this.supplierDir = business.getSupplierDirectory();
        this.userProcessContainer = userProcessContainer;
//        this.user= user;
        this.userAccount = userAccount;
        this.business = business;
        customerNameJLabel.setText(userAccount.getUserName());
        locationJLabel.setText(userAccount.getPerson().getLocation().getCity());
//        for(Customer c: business.getCustomerDirectory().getCustomerList()){
//        if(c.getPerson().getName().equals(user.getPerson().getName())){
//         customerNameJLabel.setText(c.getPerson().getName());
//        }
//        }
//       



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerNameJLabel = new javax.swing.JLabel();
        browsePCJButton = new javax.swing.JButton();
        ManageFAJButton = new javax.swing.JButton();
        complainJButton = new javax.swing.JButton();
        bookOrderJButton = new javax.swing.JButton();
        viewReturnRequestJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        locationJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("My Work Area (Customer Role)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        viewJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewJButton.setText("View Orders >>");
        viewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJButtonActionPerformed(evt);
            }
        });
        add(viewJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 223, 300, 30));

        jLabel2.setText("Hello!:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel3.setText("Welcome!");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 20));

        customerNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(customerNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 30));

        browsePCJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        browsePCJButton.setText("Browse Product Catalog >>");
        browsePCJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsePCJButtonActionPerformed(evt);
            }
        });
        add(browsePCJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 130, 300, -1));

        ManageFAJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageFAJButton.setText("View Transaction History >>");
        ManageFAJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageFAJButtonActionPerformed(evt);
            }
        });
        add(ManageFAJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 300, -1));

        complainJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        complainJButton.setText("View Complain Result  >>");
        complainJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainJButtonActionPerformed(evt);
            }
        });
        add(complainJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 300, 30));

        bookOrderJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookOrderJButton.setText("Book Order >>");
        bookOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookOrderJButtonActionPerformed(evt);
            }
        });
        add(bookOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 300, -1));

        viewReturnRequestJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewReturnRequestJButton.setText("View Return Product Request Result");
        viewReturnRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReturnRequestJButtonActionPerformed(evt);
            }
        });
        add(viewReturnRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 300, 30));

        jLabel4.setText("Your Location is:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        locationJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        locationJLabel.setText("jLabel5");
        add(locationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void viewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJButtonActionPerformed
        // TODO add your handling code here:
//       for(Customer c: business.getCustomerDirectory().getCustomerList()){
//        if(c.equals(userAccount.getPerson())){
        ViewOrdersJPanel vos = new ViewOrdersJPanel(userProcessContainer, business, customer, userAccount);
        userProcessContainer.add("ViewOrdersJPanel", vos);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
//        }
//        }


    }//GEN-LAST:event_viewJButtonActionPerformed

    private void ManageFAJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageFAJButtonActionPerformed
        ViewTransactionHistoryJPanel viewTransactionHistoryJPanel = new ViewTransactionHistoryJPanel(userProcessContainer, business, customer, userAccount);
        userProcessContainer.add("ViewTransactionHistoryJPanel", viewTransactionHistoryJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageFAJButtonActionPerformed

    private void complainJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainJButtonActionPerformed
        // TODO add your handling code here:
        ViewComplainResultJPanel viewComplainResultJPanel = new ViewComplainResultJPanel(userProcessContainer, business, customer, userAccount);
        userProcessContainer.add("ViewComplainResultJPanel", viewComplainResultJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_complainJButtonActionPerformed

    private void bookOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookOrderJButtonActionPerformed
        // TODO add your handling code here:
        BookOrderJPanel bpjp = new BookOrderJPanel(userProcessContainer, business, customer, userAccount);
        userProcessContainer.add("BookOrderJPane", bpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_bookOrderJButtonActionPerformed

    private void viewReturnRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReturnRequestJButtonActionPerformed
        // TODO add your handling code here:

        ViewReturnRequestJPanel viewReturnRequestJPanel = new ViewReturnRequestJPanel(userProcessContainer, business, userAccount);
        userProcessContainer.add("ViewReturnRequestJPanel", viewReturnRequestJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReturnRequestJButtonActionPerformed

    private void browsePCJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsePCJButtonActionPerformed
        // TODO add your handling code here:
        BrowseProductCatalogJPanel bpcjp = new BrowseProductCatalogJPanel(userProcessContainer, business);
        userProcessContainer.add("BrowseProductCatalogJPanel", bpcjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_browsePCJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageFAJButton;
    private javax.swing.JButton bookOrderJButton;
    private javax.swing.JButton browsePCJButton;
    private javax.swing.JButton complainJButton;
    private javax.swing.JLabel customerNameJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel locationJLabel;
    private javax.swing.JButton viewJButton;
    private javax.swing.JButton viewReturnRequestJButton;
    // End of variables declaration//GEN-END:variables
}
