/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerRole.Login;

import userInterface.AmazonRole.SalesDeptRole.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Product.Product;

/**
 *
 * @author Administrator
 */
public class ViewProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageProductJPanel
     */
    JPanel userProcessContainer;
    Product product;
    public ViewProductJPanel(JPanel userProcessContainer,
    Product product) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.product = product;
          nameField.setText(product.getName());
        actualPriceField.setText(String.valueOf(product.getActualPrice()));
        idField1.setText(String.valueOf(product.getProductId()));
        productQField.setText(String.valueOf(product.getQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        actualPriceField = new javax.swing.JTextField();
        idField1 = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        backButton1 = new javax.swing.JButton();
        productQField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Product Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Product Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 99, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Product ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 139, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 179, -1, 30));

        actualPriceField.setEditable(false);
        actualPriceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        actualPriceField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        actualPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualPriceFieldActionPerformed(evt);
            }
        });
        add(actualPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 159, -1));

        idField1.setEditable(false);
        idField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(idField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 159, -1));

        nameField.setEditable(false);
        nameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 159, -1));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        productQField.setEditable(false);
        productQField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productQField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        productQField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQFieldActionPerformed(evt);
            }
        });
        add(productQField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 159, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Product Quantity:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 220, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void actualPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualPriceFieldActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void productQFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productQFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualPriceField;
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField idField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField productQField;
    // End of variables declaration//GEN-END:variables
}
