/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerRole;

import business.Business;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import system.Customer.Customer;
import system.Enterprise.Enterprise;
import system.NetWork.NetWork;
import system.Organization.Organization;
import system.Person.Person;
import system.Role.PCustomerRole;
import system.UserAccount.UserAccount;

/**
 *
 * @author Administrator
 */
public class CustomerRegister2JPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerRegister2JPanel
     */
    JPanel container;
//   Customer c;
    Person p;
    Business business;
    public CustomerRegister2JPanel(  JPanel container,
Person p, 
//            Customer c,
    Business business) {
        initComponents();
        this.container =container;
//       this.c = c;
        this.p =p;
        this.business =business;
    }
    private void createUserAccount(){
          UserAccount ua = new UserAccount();
                String userName = userNameJTextField.getText();
                String password = String.valueOf(passwordJPasswordField.getPassword());
//           boolean check =business.getUserAccountDirectoty().checkUserName(username);
//      if(check==true){
//                 JOptionPane.showMessageDialog(null, "UserName has exsited!");
//               
//             }else{
                 for (NetWork n : business.getNetWorkDirectory().getNetWorkList()) {
            boolean check = business.getUserAccountDirectoty().checkUserName(userName);
            if (check == true) {
                JOptionPane.showMessageDialog(null, "UserName has exsited!");
                return;
            }
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                boolean checkE = e.getUserAccountDirectoty().checkUserName(userName);
                if (checkE == true) {
                    JOptionPane.showMessageDialog(null, "UserName has exsited!");
                    return;
                }
                for (Organization organization : e.getDepartmentDirectory().getDepartmentList()) {
                    boolean checkO = organization.getUserAccountDirectoty().checkUserName(userName);
                    if (checkO == true) {
                        JOptionPane.showMessageDialog(null, "UserName has exsited!");
                        return;
                    }
                }
            }
        }
          business.getUserAccountDirectoty().getUserAccountList().add(ua);
          
          ua.setUserName(userName);
          ua.setPassword(password);
          ua.setRole(new PCustomerRole());
          ua.setPerson(p);
        
//    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        createJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Customer Register");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel2.setText("UserName:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });
        add(createJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Create UserAccount");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        createUserAccount();
//       Customer c= business.getCustomerDirectory().creCustomer(p);
//       c.set
        
    }//GEN-LAST:event_createJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
