/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ShippingEnterpriseRole.AccountingDeptRole;

import userInterface.ShippingEnterpriseRole.*;
import business.Business;
import business.ShippingEnterprise.ShippingEnterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Enterprise.Enterprise;
import system.Organization.Organization;
import system.UserAccount.UserAccount;

/**
 *
 * @author Administrator
 */
public class AccountDeptWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShippingEnterpriseJPanel
     */
     JPanel container;
//    JPanel userProcessContainer;
//    Supplier supplier;
     Business business;
    Enterprise e;
 UserAccount ua;
    Organization o;
    public AccountDeptWorkAreaJPanel(JPanel container, 

//    Supplier supplier;
            Business business,
    Enterprise e,
 UserAccount ua,
    Organization o) {
        initComponents();
        this.container = container;
         this.e =e;
        this.ua =ua;
        this.o=o;
        this.business=business;
        sdptNameJLabel.setText(ua.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sdptNameJLabel = new javax.swing.JLabel();
        viewTransactionButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Accounting Dept Role:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        sdptNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sdptNameJLabel.setText("jLabel2");
        add(sdptNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 100, 30));

        viewTransactionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewTransactionButton.setText("View Transaction History >>");
        viewTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionButtonActionPerformed(evt);
            }
        });
        add(viewTransactionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionButtonActionPerformed
        ViewTransactionHistoryJPanel viewTransactionHistoryJPanel = new ViewTransactionHistoryJPanel(container, business,e,ua);
        container.add("ViewTransactionHistoryJPanel", viewTransactionHistoryJPanel);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);

    }//GEN-LAST:event_viewTransactionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel sdptNameJLabel;
    private javax.swing.JButton viewTransactionButton;
    // End of variables declaration//GEN-END:variables
}
