/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ShippingEnterpriseRole;

import business.ShippingEnterprise.ShippingEnterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import system.Employee.Employee;
import system.Enterprise.Enterprise;
import system.Organization.DepartmentDirectory;
import system.Organization.Organization;
import system.Person.Person;

/**
 *
 * @author Administrator
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeJPanel
     */
    JPanel container;
    DepartmentDirectory departmentDirectory;
//    Business business;
//    ShippingEnterprise shippingEnterprise;
    Enterprise e;
    public ManageEmployeeJPanel( JPanel container,Enterprise e) {
        initComponents();
        this.container = container;
//        this.business =business;
//        shippingEnterprise = (ShippingEnterprise)enterprise;
       this.e =e;
        this.departmentDirectory =e.getDepartmentDirectory();
        populateOrganization();
    }
    private void populateOrganization(){
     for(Organization o: departmentDirectory.getDepartmentList()){
                     orgJComboBox.addItem(o);
                     orgNameJComboBox.addItem(o);
     }
    }
     private void createEmployee(){
     Organization org = (Organization)orgNameJComboBox.getSelectedItem();
     Person p = e.getPersonDirectory().crePerson();
     Employee emp = org.getEmployeeDirectory().creEmployee();
     emp.setEmpId(empIdJTextField.getText());
     emp.setEmpName(empNameJTextField.getText());
     }
    private void popateTable(Organization o){
         DefaultTableModel model = (DefaultTableModel)empJTable.getModel();
         model.setNumRows(0);
         for(Employee e: o.getEmployeeDirectory().getEmployeeList()){
          Object [] row = new Object [2];
          row[0]= e.getEmpId();
          row[1]=e.getEmpName();
          model.addRow(row);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        empJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        empNameJTextField = new javax.swing.JTextField();
        orgNameJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        creJButton = new javax.swing.JButton();
        orgJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        empIdJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(empJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 340, 110));

        jLabel1.setText("Employee Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));
        add(empNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 120, -1));

        add(orgNameJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 170, -1));

        jLabel2.setText("Organization:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        creJButton.setText("Create");
        creJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creJButtonActionPerformed(evt);
            }
        });
        add(creJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        orgJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgJComboBoxActionPerformed(evt);
            }
        });
        add(orgJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, -1));

        jLabel3.setText("Organization:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel4.setText("Employee ID:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        add(empIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void orgJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgJComboBoxActionPerformed
        // TODO add your handling code here:
        popateTable((Organization)orgJComboBox.getSelectedItem());
    }//GEN-LAST:event_orgJComboBoxActionPerformed

    private void creJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creJButtonActionPerformed
        // TODO add your handling code here:
        createEmployee();
    }//GEN-LAST:event_creJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton creJButton;
    private javax.swing.JTextField empIdJTextField;
    private javax.swing.JTable empJTable;
    private javax.swing.JTextField empNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox orgJComboBox;
    private javax.swing.JComboBox orgNameJComboBox;
    // End of variables declaration//GEN-END:variables
}
