/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SupplierRole.AccountingDeptRole;

import business.Business;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import system.Enterprise.Enterprise;
import system.NetWork.NetWork;
import system.Order.OrderItem;
import system.Organization.Organization;
import system.Product.Product;
import system.Transcation.Transcation;
import system.UserAccount.UserAccount;

/**
 *
 * @author Administrator
 */
public class ViewTransactionHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewTransactionHistoryJPanel
     */
    JPanel container;
    Business business;
    Enterprise e;
    Organization o;
    UserAccount ua;
    Organization accO;
    Organization pO;

    public ViewTransactionHistoryJPanel(
            JPanel container,
            Business business,
            Enterprise e,
            Organization o,
            UserAccount ua) {
        initComponents();
        this.container = container;
        this.business = business;
        this.o = o;
        this.e = e;
        this.ua = ua;

        for (Organization or : e.getDepartmentDirectory().getDepartmentList()) {
            if (or.getType().equals(Organization.OrganizationType.EnterpriseAccountingDept)) {
                this.accO = or;
            }
        }
        for(NetWork n: business.getNetWorkDirectory().getNetWorkList()){
        for(Enterprise en : n.getEnterpriseDirectory().getEnterpriseList()){
            if(en.getEnterpriseType().equals(Enterprise.EnterpriseType.LocalRetalier)){
                 for (Organization or : en.getDepartmentDirectory().getDepartmentList()) {
            if (or.getType().equals(Organization.OrganizationType.ProductManageDept)) {
                this.pO = or;
            }
        }
            }
      
        }
        }
     

        popData();
    }

    private void popData() {
        DefaultTableModel model = (DefaultTableModel) customerTransactionJTable.getModel();
        model.setNumRows(0);
        for (Transcation t : accO.getTranscationList().getTranscationList()) {
//               if(t.getReceiver().equals(e)){
            Object[] row = new Object[8];
            row[0] = t;
//            row[1] = t.getO();
            if (t.getO() != null) {
                     row[1]=t.getO();
//                for (Product p : pO.getProductCatalog().getProductList()) {
//                    for (OrderItem oi : t.getO().getOis()) {
//                        if (p.equals(oi.getProduct())) {
//                            row[1] = oi.getProduct().getName();
//                        } 
//                    }
//                }
            }else {
                            row[1] = t.getMessage();
                        }
            row[2]=t.getMessage();
            row[3] = t.getMoneyAmount();
            row[4] = t.getIniCreater();
            row[5] = t.getReceiver();
            row[6] = t.getIniDate();
            row[7] = t.getCompleteDate();

            model.addRow(row);
        }
    }
//   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceptJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTransactionJTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acceptJButton.setText("Confirm");
        acceptJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptJButtonActionPerformed(evt);
            }
        });
        add(acceptJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Transaction History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, -1));

        customerTransactionJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Order", "Reason", "Amount", "Sender", "Receiver", "InitialDate", "CompleteDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTransactionJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 690, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void acceptJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerTransactionJTable.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }

        Transcation t = (Transcation) customerTransactionJTable.getValueAt(selectedRow, 0);
        Date curDate = new Date(System.currentTimeMillis());
        t.setCompleteDate(curDate);
        popData();
    }//GEN-LAST:event_acceptJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptJButton;
    private javax.swing.JButton backjButton1;
    private javax.swing.JTable customerTransactionJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
