/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.TempRole;

import business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Person.Person;
import system.UserAccount.UserAccount;

/**
 *
 * @author Administrator
 */
public class TempWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TempSupplierWorkAreaJPanel
     */
    JPanel container;
    Business business;
    UserAccount ua;
    Person p;

    public TempWorkAreaJPanel(
            JPanel container,
            UserAccount ua,
            Person p,
            Business business) {
        initComponents();
        this.container = container;
        this.business = business;
        this.p = p;
        this.ua = ua;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registerJButton = new javax.swing.JButton();
        viewStatusJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Temp Enterprise WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        registerJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerJButton.setText("Register");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });
        add(registerJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 90, -1));

        viewStatusJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewStatusJButton.setText("View Status");
        viewStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatusJButtonActionPerformed(evt);
            }
        });
        add(viewStatusJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatusJButtonActionPerformed
        // TODO add your handling code here:

        ViewStatusJPanel viewStatusJPanel = new ViewStatusJPanel(container, ua, business);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ViewStatusJPanel", viewStatusJPanel);
        layout.next(container);
    }//GEN-LAST:event_viewStatusJButtonActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        // TODO add your handling code here:
        //         UserAccount ua = business.getUserAccountDirectoty().creUserAccount();

        RetalierRegisterJPanel retalierRegister = new RetalierRegisterJPanel(container, p, business);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("RegisterRetalier", retalierRegister);
        layout.next(container);
    }//GEN-LAST:event_registerJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registerJButton;
    private javax.swing.JButton viewStatusJButton;
    // End of variables declaration//GEN-END:variables
}
