/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.TempRole;

import business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import system.Role.TempRole;
import system.UserAccount.UserAccount;
import system.WorkQueue.WorkRequest;

/**
 *
 * @author Administrator
 */
public class ViewStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStatusJPanel
     */
    JPanel container;
    Business business;
//    UserPerson up;
    UserAccount ua;

    public ViewStatusJPanel(JPanel container,
            UserAccount ua, Business business) {
        initComponents();
        this.container = container;
        this.business = business;
//        this.up = (UserPerson)p;
        this.ua = ua;
        populateTableData();
    }

    private void populateTableData() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setNumRows(0);
//        for(Person p: business.getPersonDirectory().getPersonList()){
//            if(p instanceof AdminPerson){
        for (WorkRequest wr : business.getWorkQueue().getWorkRequestList()) {
            if(wr.getWorkRequestType().equals(WorkRequest.WorkRequestType.TempEnterpriseRequest)&&wr.getSender().equals(ua)){
            Object[] row = new Object[5];
            row[0] = wr;    // don't need to get message
            row[1]=wr.getMessage();
            row[2] = wr.getSender().getUserName();
            row[3] = wr.getSender().getPassword();
            row[4] = wr.getStatus();
            model.addRow(row);
        }
//            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestID", "Name", "UserName", "Password", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 400, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
