/*
 * CreateProductJPanel.java
 *
 * Created on September 18, 2008, 2:54 PM
 */
package userInterface.SupplierRole.ProductManageDeptRole;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import system.Enterprise.Enterprise;
import system.Inventory.LeftProduct;
import system.Inventory.LeftProductCatalog;
import system.Organization.Organization;
import system.Product.Product;
import system.Product.ProductCatalog;

/**
 *
 * @author Rushabh
 */
public class CreateNewProductJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    ProductCatalog productCatalog;
    Enterprise e;
    LeftProductCatalog leftProductCatalog;
    Organization o;
    public CreateNewProductJPanel(JPanel userProcessContainer,
            //            ProductCatalog productCatalog
            Enterprise e,Organization o) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
//        this.productCatalog = productCatalog;
        this.e = e;
        this.o=o;
        this.productCatalog = o.getProductCatalog();
        this.leftProductCatalog = o.getLeftProductCatalog();
    }
    
    public void check() {
        int numID;
        double numTP;
        int numQ;
        double tax;
        try {
            numID = Integer.parseInt(idField.getText());
            numTP = Double.parseDouble(targetPriceField.getText());
//                = Integer.parseInt(targetPriceField.getText());
            numQ = Integer.parseInt(pQuantityField.getText());
            tax = Double.parseDouble(taxJTextField.getText());
            boolean check = productCatalog.checkProductId(numID);
            if (check == true) {
                JOptionPane.showMessageDialog(null, "ID should be unique!");
                return;
            }
            if (numID > 0 && numTP > 0 && numQ > 0 && tax >= 0) {
                
                Product product = productCatalog.newProduct();
                LeftProduct leftProduct = leftProductCatalog.newLeftProduct();
                leftProduct.setProduct(product);
                
                product.setProductId(numID);
                product.setName(nameField1.getText());
                product.setTargetPrice(numTP);
                product.setQuantity(Integer.parseInt(pQuantityField.getText()));
                product.setTax(tax);
                product.setLeftProduct(leftProduct);

//            product.getLeftProduct().setLeftQuantity(product.getQuantity());
                leftProduct.setLeftQuantity(product.getQuantity());
            }
            
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Invalid Information!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        targetPriceField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pQuantityField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        taxJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create New Product");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Product ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 130, 100, 30));

        idField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product Target Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 180, 170, 30));

        targetPriceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(targetPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 210, 30));

        createButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createButton.setText("Add Product");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Product Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 30));

        nameField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Product Tax:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 110, 30));

        pQuantityField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(pQuantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Product Quantity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 30));

        taxJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(taxJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 210, 30));
    }// </editor-fold>//GEN-END:initComponents
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:

        check();
        
}//GEN-LAST:event_createButtonActionPerformed
    
    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameField1;
    private javax.swing.JTextField pQuantityField;
    private javax.swing.JTextField targetPriceField;
    private javax.swing.JTextField taxJTextField;
    // End of variables declaration//GEN-END:variables
}
