/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SupplierRole.ProductManageDeptRole;


import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Product.Product;

/**
 *
 * @author Goku
 */
public class ManageProductPanel extends javax.swing.JPanel {

    
    JPanel userProcessContainer;
    Product product;
    public ManageProductPanel(JPanel upc, Product product) {
        initComponents();
        this.userProcessContainer = upc;
        this.product = product;
        
        nameField.setText(product.getName());
        targetPriceField.setText(String.valueOf(product.getTargetPrice()));
        quantityField.setText(String.valueOf(product.getLeftProduct().getLeftQuantity()));
        idField1.setText(String.valueOf(product.getProductId()));
        taxField.setText(String.valueOf(product.getTax()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        targetPriceField = new javax.swing.JTextField();
        idField1 = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        backButton1 = new javax.swing.JButton();
        saveButton1 = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        taxField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Product Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Product Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Product ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product Target Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        targetPriceField.setEditable(false);
        targetPriceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        targetPriceField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        targetPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetPriceFieldActionPerformed(evt);
            }
        });
        add(targetPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 159, -1));

        idField1.setEditable(false);
        idField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(idField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 159, -1));

        nameField.setEditable(false);
        nameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 159, -1));

        backButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        saveButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveButton1.setText("SAVE");
        saveButton1.setEnabled(false);
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        add(saveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 70, 30));

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateButton.setText("Update Product");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 176, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tax:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        quantityField.setEditable(false);
        quantityField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });
        add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 159, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Quantity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        taxField.setEditable(false);
        taxField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taxField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        taxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxFieldActionPerformed(evt);
            }
        });
        add(taxField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 159, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed

        product.setName(nameField.getText());
        product.setTargetPrice(Double.parseDouble(targetPriceField.getText()));
        product.setQuantity(Integer.parseInt(quantityField.getText()));
        product.getLeftProduct().setLeftQuantity(product.getQuantity());
        product.setTax(Double.parseDouble(taxField.getText()));
        nameField.setEditable(false);
        targetPriceField.setEditable(false);
        quantityField.setEditable(false);
        taxField.setEditable(false);
        saveButton1.setEnabled(false);
        

    }//GEN-LAST:event_saveButton1ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        nameField.setEditable(true);
        targetPriceField.setEditable(true); 
        quantityField.setEditable(true);
        saveButton1.setEnabled(true);
        taxField.setEditable(true);

    }//GEN-LAST:event_updateButtonActionPerformed

    private void targetPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetPriceFieldActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void taxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField idField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton saveButton1;
    private javax.swing.JTextField targetPriceField;
    private javax.swing.JTextField taxField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
