/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package userInterface.SupplierRole.ProductManageDeptRole;


import java.awt.CardLayout;
import javax.swing.JPanel;
import system.Enterprise.Enterprise;
import system.Organization.Organization;
import system.UserAccount.UserAccount;

/**
 *
 * @author Rushabh
 */
public class ProductManageDeptWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
//    Supplier supplier;
    Enterprise e;
 UserAccount ua;
    Organization o;
    /** Creates new form ProductManagerWorkAreaJPanel */
    public ProductManageDeptWorkAreaJPanel(JPanel userProcessContainer,UserAccount ua,Enterprise e,Organization o) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
//        this.supplier = (Supplier)e;
        this.e =e;
        this.ua =ua;
        this.o=o;
        lblSupplierName.setText(ua.getUserName());
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        managePButton = new javax.swing.JButton();
        lblSupplierName = new javax.swing.JLabel();
        viewInventoryJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area (Product Manage Dept Role) :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        managePButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        managePButton.setText("Manage Inventory >>");
        managePButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePButtonActionPerformed(evt);
            }
        });
        add(managePButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 260, -1));

        lblSupplierName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(lblSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 130, 30));

        viewInventoryJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewInventoryJButton.setText("View Inventory Request >>");
        viewInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryJButtonActionPerformed(evt);
            }
        });
        add(viewInventoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 260, 30));
    }// </editor-fold>//GEN-END:initComponents
    private void managePButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePButtonActionPerformed
        
        ManageProductCatalogJPanel mpcjp = new ManageProductCatalogJPanel(userProcessContainer, e,o);
        userProcessContainer.add("ManageProductCatalogJPanel", mpcjp);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_managePButtonActionPerformed

    private void viewInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryJButtonActionPerformed
        // TODO add your handling code here:
           ViewInventoryRequestJPanel viewInventoryRequestJPanel = new ViewInventoryRequestJPanel(userProcessContainer, e,ua,o);
        userProcessContainer.add("ViewInventoryRequestJPanel", viewInventoryRequestJPanel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewInventoryJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JButton managePButton;
    private javax.swing.JButton viewInventoryJButton;
    // End of variables declaration//GEN-END:variables
}
